name: Make Sphinx Docs and Upload to GCS

on:
  workflow_dispatch:
    inputs:
      libVersion:
        description: Library Version
        required: true
        default: x.x.x
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[dev]
        python -m pip install -r docs/requirements.txt
    - name: Build & Zip Sphinx HTML Docs
      run: |
        cd docs/
        make clean html
        cd _build/html
        tar -czvf ../../${{ github.event.inputs.libVersion }}.tar.gz .
    - name: Upload to Google Cloud Storage
      uses: 'google-github-actions/upload-cloud-storage@v2'
      with:
        path: 'docs/${{ github.event.inputs.libVersion }}.tar.gz'
        destination: 'ua-web-ci-prod-docs-transfer/libraries/python/${{ github.event.inputs.libVersion }}.tar.gz'
        parent: false
