name: PyPI Test Build and Upload

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build twine
    - name: Build binary wheel and source tarball
      run: |
        python -m build
        twine check dist/*
    - name: Publish to Test PyPI
      if: ${{github.repository == 'urbanairship/python-library-dev'}}
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_TEST_TOKEN }}
        repository-url: https://test.pypi.org/legacy/
