name: Release Publish and Upload

on:
  release:
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.9 for build
      uses: actions/setup-python@v1
      with:
        python-version: 3.13

    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build binary wheel and source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
    - name: Publish to Pypi
      if: ${{github.repository == 'urbanairship/python-library-dev'}}
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_TOKEN_URBANAIRSHIP }}
