name: Python Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt
      - name: Type check with mypy
        run: |
          mypy --config-file=pyproject.toml --ignore-missing-imports --disable-error-code=no-any-return urbanairship/
      - name: Test with pytest
        run: |
          python -m pytest
      - name: Build package
        run: |
          python -m pip install build twine
          python -m build
          twine check dist/*
